/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg7_davidbendeck;

import Hilos.TiempoEspera;
import Usuarios.Admin;
import Usuarios.Artista;
import Usuarios.Banda;
import Usuarios.Fan;
import Usuarios.Solista;
import java.awt.Dialog;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author davidbendeck
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_LogIn = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_Nickname_LogIn = new javax.swing.JTextField();
        CB_Usuario_LogIn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        PF_Password_LogIn = new javax.swing.JPasswordField();
        B_LogIn_LogIn = new javax.swing.JButton();
        D_MenuAdmin = new javax.swing.JDialog();
        TP_MenuAdmin = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        TP_AdministrarUsuario = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        CB_Nickname_AdminArtista = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        B_Eliminar_AdminArtista = new javax.swing.JButton();
        B_Cargar_AdminArtista = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CB_Nickname_AdminFan = new javax.swing.JComboBox<>();
        B_Eliminar_AdminFan = new javax.swing.JButton();
        B_Cargar_AdminFan = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        D_MenuArtista = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        D_MenuFan = new javax.swing.JDialog();
        D_Register = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TF_Nickname_Register = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PF_Password_Register = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TF_Name_Register = new javax.swing.JTextField();
        B_Register_Register = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TF_Genero_Register = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CB_Usuario_Register = new javax.swing.JComboBox<>();
        CB_TipoArtista_Register = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        TF_Integrantes_Register = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TF_Edad_Register = new javax.swing.JTextField();
        D_Cargar = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        PB_Cargar = new javax.swing.JProgressBar();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        B_LogIn = new javax.swing.JButton();
        B_Registrarse = new javax.swing.JButton();
        B_Salir = new javax.swing.JButton();

        jLabel1.setText("Nickname");

        TF_Nickname_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Nickname_LogInActionPerformed(evt);
            }
        });

        CB_Usuario_LogIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Artista", "Fan", " " }));

        jLabel2.setText("Password");

        PF_Password_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_Password_LogInActionPerformed(evt);
            }
        });

        B_LogIn_LogIn.setText("Log In");
        B_LogIn_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_LogIn_LogInMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_LogIn_LogIn)
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CB_Usuario_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Nickname_LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(PF_Password_LogIn))
                .addGap(151, 151, 151))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(CB_Usuario_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_Nickname_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PF_Password_LogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(B_LogIn_LogIn)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout D_LogInLayout = new javax.swing.GroupLayout(D_LogIn.getContentPane());
        D_LogIn.getContentPane().setLayout(D_LogInLayout);
        D_LogInLayout.setHorizontalGroup(
            D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_LogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_LogInLayout.setVerticalGroup(
            D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        CB_Nickname_AdminArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Nickname_AdminArtistaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nickname");

        B_Eliminar_AdminArtista.setText("Eliminar");
        B_Eliminar_AdminArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Eliminar_AdminArtistaMouseClicked(evt);
            }
        });

        B_Cargar_AdminArtista.setText("Cargar");
        B_Cargar_AdminArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Cargar_AdminArtistaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(77, 77, 77)
                .addComponent(CB_Nickname_AdminArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_Eliminar_AdminArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Cargar_AdminArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Nickname_AdminArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(B_Cargar_AdminArtista))
                .addGap(39, 39, 39)
                .addComponent(B_Eliminar_AdminArtista)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        TP_AdministrarUsuario.addTab("Artista", jPanel5);

        jLabel13.setText("Nickname");

        CB_Nickname_AdminFan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Nickname_AdminFanActionPerformed(evt);
            }
        });

        B_Eliminar_AdminFan.setText("Eliminar");
        B_Eliminar_AdminFan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Eliminar_AdminFanMouseClicked(evt);
            }
        });

        B_Cargar_AdminFan.setText("Cargar");
        B_Cargar_AdminFan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Cargar_AdminFanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel13)
                .addGap(64, 64, 64)
                .addComponent(CB_Nickname_AdminFan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_Eliminar_AdminFan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Cargar_AdminFan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Nickname_AdminFan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(B_Cargar_AdminFan))
                .addGap(60, 60, 60)
                .addComponent(B_Eliminar_AdminFan)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        TP_AdministrarUsuario.addTab("Fan", jPanel6);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_AdministrarUsuario)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_AdministrarUsuario)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        TP_MenuAdmin.addTab("Modificar Usuario", jPanel4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        TP_MenuAdmin.addTab("Bitácora", jPanel7);

        javax.swing.GroupLayout D_MenuAdminLayout = new javax.swing.GroupLayout(D_MenuAdmin.getContentPane());
        D_MenuAdmin.getContentPane().setLayout(D_MenuAdminLayout);
        D_MenuAdminLayout.setHorizontalGroup(
            D_MenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_MenuAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_MenuAdmin)
                .addContainerGap())
        );
        D_MenuAdminLayout.setVerticalGroup(
            D_MenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_MenuAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_MenuAdmin)
                .addContainerGap())
        );

        javax.swing.GroupLayout D_MenuArtistaLayout = new javax.swing.GroupLayout(D_MenuArtista.getContentPane());
        D_MenuArtista.getContentPane().setLayout(D_MenuArtistaLayout);
        D_MenuArtistaLayout.setHorizontalGroup(
            D_MenuArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_MenuArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_MenuArtistaLayout.setVerticalGroup(
            D_MenuArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_MenuArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout D_MenuFanLayout = new javax.swing.GroupLayout(D_MenuFan.getContentPane());
        D_MenuFan.getContentPane().setLayout(D_MenuFanLayout);
        D_MenuFanLayout.setHorizontalGroup(
            D_MenuFanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        D_MenuFanLayout.setVerticalGroup(
            D_MenuFanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel3.setText("Nickname");

        jLabel4.setText("Password");

        jLabel5.setText("Nombre");

        B_Register_Register.setText("Register");
        B_Register_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Register_RegisterMouseClicked(evt);
            }
        });

        jLabel6.setText("Genero musical");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Solo se tomarán en cuenta los\ncampos que correspodan al \ntipo de usuario y al tipo de \nartista");
        jScrollPane1.setViewportView(jTextArea1);

        CB_Usuario_Register.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artista", "Fan" }));
        CB_Usuario_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Usuario_RegisterActionPerformed(evt);
            }
        });

        CB_TipoArtista_Register.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solista", "Banda" }));
        CB_TipoArtista_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_TipoArtista_RegisterActionPerformed(evt);
            }
        });

        jLabel15.setText("Numero de integrantes");

        jLabel16.setText("Edad");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(B_Register_Register)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_Integrantes_Register))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PF_Password_Register, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_Name_Register, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_Genero_Register)
                            .addComponent(TF_Nickname_Register)
                            .addComponent(TF_Edad_Register, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CB_TipoArtista_Register, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_Usuario_Register, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_Nickname_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Usuario_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PF_Password_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_TipoArtista_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_Name_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TF_Edad_Register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TF_Integrantes_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TF_Genero_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_Register_Register)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout D_RegisterLayout = new javax.swing.GroupLayout(D_Register.getContentPane());
        D_Register.getContentPane().setLayout(D_RegisterLayout);
        D_RegisterLayout.setHorizontalGroup(
            D_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        D_RegisterLayout.setVerticalGroup(
            D_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PB_Cargar.setMaximum(3);

        jLabel14.setText("Espere por favor ...");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel14))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(PB_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(PB_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_CargarLayout = new javax.swing.GroupLayout(D_Cargar.getContentPane());
        D_Cargar.getContentPane().setLayout(D_CargarLayout);
        D_CargarLayout.setHorizontalGroup(
            D_CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_CargarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_CargarLayout.setVerticalGroup(
            D_CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_CargarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_LogIn.setText("Log In");
        B_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_LogInMouseClicked(evt);
            }
        });

        B_Registrarse.setText("Registrarse (Fan)");
        B_Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_RegistrarseMouseClicked(evt);
            }
        });

        B_Salir.setText("Salir");
        B_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(B_LogIn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(B_Salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 261, Short.MAX_VALUE)
                .addComponent(B_Registrarse)
                .addGap(259, 259, 259))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(B_LogIn)
                .addGap(66, 66, 66)
                .addComponent(B_Registrarse)
                .addGap(61, 61, 61)
                .addComponent(B_Salir)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_SalirMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_B_SalirMouseClicked

    private void B_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_LogInMouseClicked
        // TODO add your handling code here:
        
        D_LogIn.pack();
        D_LogIn.setVisible(true);
    }//GEN-LAST:event_B_LogInMouseClicked

    private void B_LogIn_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_LogIn_LogInMouseClicked
        // TODO add your handling code here:
        
        String usuario = (String) CB_Usuario_LogIn.getSelectedItem();
        boolean pass = false;
        
        if (usuario.equals("Administrador")) {
            if (TF_Nickname_LogIn.getText().equals(Leo.getNickname())) {
                if (PF_Password_LogIn.getText().equals(Leo.getPassword())) {
                    D_LogIn.setVisible(false);
                    D_MenuAdmin.pack();
                    D_MenuAdmin.setVisible(true);
                    pass = true;
                }
            }
        } else if (usuario.equals("Fan")){
            for (Fan fan : fans) {
                if (TF_Nickname_LogIn.getText().equals(fan.getNickname())) {
                    if (PF_Password_LogIn.getText().equals(fan.getPassword())) {
                        D_LogIn.setVisible(false);
                        fanActual = fan;
                        D_MenuFan.pack();
                        D_MenuFan.setVisible(true);
                        pass = true;
                    }
                }
            }
        } else {
            for (Artista artista : artistas) {
                if (TF_Nickname_LogIn.getText().equals(artista.getNickname())) {
                    if (PF_Password_LogIn.getText().equals(artista.getPassword())) {
                        D_LogIn.setVisible(false);
                        artistaActual = artista;
                        D_MenuArtista.pack();
                        D_MenuArtista.setVisible(true);
                        pass = true;
                    }
                }
            }
        }
        
        if (!pass) {
            JOptionPane.showMessageDialog(D_LogIn, "Nickname o contraseña incorrecto(s)");
        }
    }//GEN-LAST:event_B_LogIn_LogInMouseClicked

    private void TF_Nickname_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Nickname_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Nickname_LogInActionPerformed

    private void PF_Password_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_Password_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF_Password_LogInActionPerformed

    private void B_RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RegistrarseMouseClicked
        // TODO add your handling code here:
        
        D_Register.pack();
        D_Register.setVisible(true);
        /*CB_TipoArtista_Register.setVisible(false);
        TF_Edad_Register.setVisible(false);
        TF_Genero_Register.setVisible(false);
        TF_Integrantes_Register.setVisible(false);*/
    }//GEN-LAST:event_B_RegistrarseMouseClicked

    private void B_Register_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Register_RegisterMouseClicked
        // TODO add your handling code here:
        
        String usuario = (String) CB_Usuario_Register.getSelectedItem();
        
        String nickname = TF_Name_Register.getText();
        String password = PF_Password_Register.getText();
        String name = TF_Name_Register.getText();
        
        D_Register.setVisible(false);
        
        TiempoEspera wait;
        wait = new TiempoEspera(PB_Cargar,D_Cargar, 5);
        wait.start();
        D_Cargar.pack();
        D_Cargar.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_Cargar.setVisible(true);
        try {
            wait.join();
        } catch (InterruptedException ex) {
            System.out.println(ex);
        }
        
        if (usuario.equals("Artista")) {
            String genero = TF_Genero_Register.getText();
            if (CB_TipoArtista_Register.getSelectedItem().equals("Solista")) {
                int edad = Integer.parseInt(TF_Edad_Register.getText());
                artistas.add(new Solista(edad, genero, nickname, password, name));
            } else {
                int integrantes = Integer.parseInt(TF_Integrantes_Register.getText());
                artistas.add(new Banda(integrantes, genero, nickname, password, name));
                
            }
            guardarArtistas(artistas);
        } else {
            fans.add(new Fan(nickname, password, name));
            guardarFans(fans);
        }
        
        D_LogIn.pack();
        D_LogIn.setVisible(true);
        JOptionPane.showMessageDialog(D_LogIn, "Proceso completado");
    }//GEN-LAST:event_B_Register_RegisterMouseClicked

    private void CB_Usuario_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Usuario_RegisterActionPerformed
        // TODO add your handling code here:
        /*if (CB_Usuario_Register.getSelectedItem().equals("Artista")) {
            CB_TipoArtista_Register.setVisible(true);
            TF_Genero_Register.setVisible(true);
        }
        else {
            CB_TipoArtista_Register.setVisible(false);
            TF_Genero_Register.setVisible(false);
        }*/
    }//GEN-LAST:event_CB_Usuario_RegisterActionPerformed

    private void CB_TipoArtista_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_TipoArtista_RegisterActionPerformed
        // TODO add your handling code here:
       /* if (CB_TipoArtista_Register.isVisible()) {
            if (CB_TipoArtista_Register.getSelectedItem().equals("Solista")) {
                TF_Edad_Register.setVisible(true);
                TF_Integrantes_Register.setVisible(false);
            } else {
                TF_Integrantes_Register.setVisible(true);
                TF_Edad_Register.setVisible(false);
            }
        }*/
    }//GEN-LAST:event_CB_TipoArtista_RegisterActionPerformed

    private void B_Cargar_AdminFanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Cargar_AdminFanMouseClicked
        // TODO add your handling code here:
        D_MenuAdmin.setVisible(false);
        TiempoEspera wait;
        wait = new TiempoEspera(PB_Cargar,D_Cargar, 3);
        System.out.println("objeto creado ");
        wait.start();
        D_Cargar.pack();
        D_Cargar.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_Cargar.setVisible(true);
        try {
            wait.join();
        } catch (InterruptedException ex) {
            System.out.println(ex);
        }
        D_MenuAdmin.pack();
        D_MenuAdmin.setVisible(true);
        JOptionPane.showMessageDialog(D_MenuAdmin, "Proceso completado");
        for (Fan f : fans) {
            CB_Nickname_AdminFan.addItem(f);
        }
    }//GEN-LAST:event_B_Cargar_AdminFanMouseClicked

    private void B_Eliminar_AdminFanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Eliminar_AdminFanMouseClicked
        // TODO add your handling code here:

        Fan fan = (Fan) CB_Nickname_AdminFan.getSelectedItem();
        if (fan != null) {
            fans.remove(fan);
            guardarFans(fans);
            CB_Nickname_AdminFan.removeAllItems();
            for (Fan f : fans) {
                CB_Nickname_AdminFan.addItem(f);
            }
        }
    }//GEN-LAST:event_B_Eliminar_AdminFanMouseClicked

    private void CB_Nickname_AdminFanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Nickname_AdminFanActionPerformed
        // TODO add your handling code here:

        Fan fan = (Fan) CB_Nickname_AdminFan.getSelectedItem();
        if (fan != null) {
            /*PF_Password_AdminFan.setText(fan.getPassword());
            TF_Nombre_AdminFan.setText(fan.getName());*/
        }
    }//GEN-LAST:event_CB_Nickname_AdminFanActionPerformed

    private void B_Cargar_AdminArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Cargar_AdminArtistaMouseClicked
        // TODO add your handling code here:
        D_MenuAdmin.setVisible(false);
        TiempoEspera wait;
        wait = new TiempoEspera(PB_Cargar,D_Cargar,3);
        wait.start();
        D_Cargar.pack();
        D_Cargar.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_Cargar.setVisible(true);
        try {
            wait.join();
        } catch (InterruptedException ex) {
            System.out.println(ex);
        }
        D_MenuAdmin.pack();
        D_MenuAdmin.setVisible(true);
        JOptionPane.showMessageDialog(D_MenuAdmin, "Proceso completado");
        for (Artista a : artistas) {
            CB_Nickname_AdminArtista.addItem(a);
        }

    }//GEN-LAST:event_B_Cargar_AdminArtistaMouseClicked

    private void B_Eliminar_AdminArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Eliminar_AdminArtistaMouseClicked
        // TODO add your handling code here:

        Artista artista = (Artista) CB_Nickname_AdminArtista.getSelectedItem();
        if (artista != null) {
            artistas.remove(artista);
            guardarArtistas(artistas);
            CB_Nickname_AdminArtista.removeAllItems();
            for (Artista a : artistas) {
                CB_Nickname_AdminArtista.addItem(a);
            }
        }
    }//GEN-LAST:event_B_Eliminar_AdminArtistaMouseClicked

    private void CB_Nickname_AdminArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Nickname_AdminArtistaActionPerformed
        // TODO add your handling code here:

        Artista artista = (Artista) CB_Nickname_AdminArtista.getSelectedItem();
        if (artista != null) {
            /*PF_Password_AdminArtista.setText(artista.getPassword());
            TF_Nombre_AdminArtista.setText(artista.getName());
            TF_Genero_AdminArtista.setText(artista.getGenero());*/
        }
    }//GEN-LAST:event_CB_Nickname_AdminArtistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //Leer Artistas
        int numArtistas;
        numArtistas = leerArtistas(artistas);
        
        //Leer fans
        int numFans;
        numFans = leerFans(fans);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Cargar_AdminArtista;
    private javax.swing.JButton B_Cargar_AdminFan;
    private javax.swing.JButton B_Eliminar_AdminArtista;
    private javax.swing.JButton B_Eliminar_AdminFan;
    private javax.swing.JButton B_LogIn;
    private javax.swing.JButton B_LogIn_LogIn;
    private javax.swing.JButton B_Register_Register;
    private javax.swing.JButton B_Registrarse;
    private javax.swing.JButton B_Salir;
    private javax.swing.JComboBox<Artista> CB_Nickname_AdminArtista;
    private javax.swing.JComboBox<Fan> CB_Nickname_AdminFan;
    private javax.swing.JComboBox<String> CB_TipoArtista_Register;
    private javax.swing.JComboBox<String> CB_Usuario_LogIn;
    private javax.swing.JComboBox<String> CB_Usuario_Register;
    private javax.swing.JDialog D_Cargar;
    private javax.swing.JDialog D_LogIn;
    private javax.swing.JDialog D_MenuAdmin;
    private javax.swing.JDialog D_MenuArtista;
    private javax.swing.JDialog D_MenuFan;
    private javax.swing.JDialog D_Register;
    private javax.swing.JProgressBar PB_Cargar;
    private javax.swing.JPasswordField PF_Password_LogIn;
    private javax.swing.JPasswordField PF_Password_Register;
    private javax.swing.JTextField TF_Edad_Register;
    private javax.swing.JTextField TF_Genero_Register;
    private javax.swing.JTextField TF_Integrantes_Register;
    private javax.swing.JTextField TF_Name_Register;
    private javax.swing.JTextField TF_Nickname_LogIn;
    private javax.swing.JTextField TF_Nickname_Register;
    private javax.swing.JTabbedPane TP_AdministrarUsuario;
    private javax.swing.JTabbedPane TP_MenuAdmin;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
    //Usuarios
    public static Admin Leo = new Admin("leobanegas","99", "Leonardo Banegas");
    
    public static Artista artistaActual;
    public static Fan fanActual;
    
    //Listas de Usuarios
    public static ArrayList<Artista> artistas = new ArrayList<>();
    public static ArrayList<Fan> fans = new ArrayList<>();
    public static ArrayList<Evento> eventos = new ArrayList<>();
    
    //Metodos de guardado
    
    public static int guardarArtistas(ArrayList<Artista> artistas) {
        int count = 0;
        try (
                FileOutputStream f = new FileOutputStream("Artistas");
                ObjectOutput o = new ObjectOutputStream(f);) {
            for (Artista artista : artistas) {
                o.writeObject(artista);
                count++;
            }
        } catch (IOException ex) { 
            System.out.println(ex);
        }
        return count;
    }
    
    public static int leerArtistas(ArrayList<Artista> artistas) {
        int count = 0;
        try (
                FileInputStream fi = new FileInputStream("Artistas");
                ObjectInputStream oi = new ObjectInputStream(fi);) {
            while (true) {
                artistas.add((Artista) oi.readObject());
                count++;
                System.out.println(count);
            }
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        System.out.println("Registros leidos" + count);
        return count;
    }
    
    public static int guardarFans(ArrayList<Fan> fans) {
        int count = 0;
        try (
                FileOutputStream f = new FileOutputStream("Fans");
                ObjectOutput o = new ObjectOutputStream(f);) {
            for (Fan fan : fans) {
                o.writeObject(fan);
                count++;
            }
        } catch (IOException ex) { 
            System.out.println(ex);
        }
        return count;
    }
    
    public static int leerFans(ArrayList<Fan> fans) {
        int count = 0;
        try (
                FileInputStream fi = new FileInputStream("Fans");
                ObjectInputStream oi = new ObjectInputStream(fi);) {
            while (true) {
                fans.add((Fan) oi.readObject());
                count++;
                System.out.println(count);
            }
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        System.out.println("Registros leidos" + count);
        return count;
    }
    
    public static int guardarEventos(ArrayList<Evento> eventos) {
        int count = 0;
        try (
                FileOutputStream f = new FileOutputStream("Eventos");
                ObjectOutput o = new ObjectOutputStream(f);) {
            for (Evento evento : eventos) {
                o.writeObject(evento);
                count++;
            }
        } catch (IOException ex) { 
            System.out.println(ex);
        }
        return count;
    }
    
    public static int leerEventos(ArrayList<Evento> eventos) {
        int count = 0;
        try (
                FileInputStream fi = new FileInputStream("Eventos");
                ObjectInputStream oi = new ObjectInputStream(fi);) {
            while (true) {
                eventos.add((Evento) oi.readObject());
                count++;
                System.out.println(count);
            }
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        System.out.println("Registros leidos" + count);
        return count;
    }
}
